name: Prisma Access IP Fetch

on:
  workflow_dispatch:  # 手動トリガー
  schedule:
    - cron: '0 23 * * *'  # 日本時間の毎朝8時に実行

jobs:
  fetch-prisma-ip:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v3

      # cURLコマンドを実行
      - name: Fetch Prisma Access IP
        run: |
          cd "$GITHUB_WORKSPACE"
          curl -X POST -d @option.txt \
            -H "header-api-key: ${{ secrets.PRISMA_API_KEY }}" \
            "https://api.prod6.datapath.prismaaccess.com/getPrismaAccessIP/v2" \
            --ssl-no-revoke -o response.json

      # 結果を確認
      - name: Display Response
        run: cat response.json

      # 結果を保存
      - name: Upload JSON Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prisma-response
          path: response.json